### ISSUE TITLE
a simple test error

### ISSUE THREAD

**Issue by zmiimz** [gronki/fortdep#1]
installed fortdep and started a simple test in the src directory (contains only valid fortran f90 files of the same project, no subfolders)

fortdep2 -o deps.inc

> no directories given; scanning recursively...
> Traceback (most recent call last):
>   File "/home/term/.local/bin/fortdep2", line 11, in <module>
>     load_entry_point('fortdep==190521', 'console_scripts', 'fortdep2')()
>   File "/home/term/.local/lib/python3.7/site-packages/fortdep-190521-py3.7.egg/fortdep2.py", line 270, in main
>   File "/home/term/.local/lib/python3.7/site-packages/fortdep-190521-py3.7.egg/fortdep2.py", line 125, in parse_source
>   File "/usr/lib64/python3.7/codecs.py", line 322, in decode
>     (result, consumed) = self._buffer_decode(data, self.errors, final)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 3110: invalid start byte

**Comment by gronki** [comment]
Thank you for the report. It seems like issue with the encoding. Do you have any diacritic characters in the comments in your code? What OS and editor are you using? With this information I will try to work on the fix.

**Comment by gronki** [comment]
For now I recommend using utf-8 encoding. I can also implement an option to manually specify the encoding as a quick fix.

**Comment by zmiimz** [comment]
Thanks, 
OS is Linux, I used different editors: kate, geany, sublime text, atom, etc.
most files have  charset=us-ascii, but some older sources have also charset=iso-8859-1

Translation to UTF-8 is an option but can produce some undesirable effects for old compilers  on the clusters and therefore is not always feasible.

**Comment by gronki** [comment]
I have pushed an update, you can now select encoding with -e option. Does it solve the issue for you?
